In [51]:
"""stored variables container,csv"""

'stored variables container,csv'

In [2]:
import re
import pandas as pd

In [36]:
def get_dic(url):
    dic ={}
    split_url = re.split('//?',url)
    scheme = split_url[0].rstrip(':')
    domain = split_url[1].strip()
    dic['url'] = url
    dic['scheme'] = scheme
    dic['domain'] = domain
    dic['brand_name'] = re.search('(\w+)-',split_url[2]).group(1)
    dic['sku_number'] = re.search('(\d+-\d+)-',split_url[2]).group(1)
    dic['color'] = re.search('\d-([A-z]+)-',split_url[2]).group(1)
    dic['occasion'] = re.search(fr"{dic['color']}-(\w+)",split_url[2]).group(1)
    dic['type']=re.search(fr"{dic['occasion']}-(.*).html",split_url[2]).group(1)
    dic['extenstion'] = re.search('\.(\w+)',split_url[2]).group(1)
    return dic

In [37]:
%store -r container

In [38]:
dic_list = []
for url in container:
    dic = get_dic(url)
    dic_list.append(dic)

In [83]:
df = pd.DataFrame(dic_list)
dic_list[:5]

[{'url': 'https://www.metroshoes.com/davinchi-60-8-black-casual-slippers.html',
  'scheme': 'https',
  'domain': 'www.metroshoes.com',
  'brand_name': 'davinchi',
  'sku_number': '60-8',
  'color': 'black',
  'occasion': 'casual',
  'type': 'slippers',
  'extenstion': 'html'},
 {'url': 'https://www.metroshoes.com/metro-35-4559-silver-party-slip-ons.html',
  'scheme': 'https',
  'domain': 'www.metroshoes.com',
  'brand_name': 'metro',
  'sku_number': '35-4559',
  'color': 'silver',
  'occasion': 'party',
  'type': 'slip-ons',
  'extenstion': 'html'},
 {'url': 'https://www.metroshoes.com/davinchi-14-1382-black-formal-derby.html',
  'scheme': 'https',
  'domain': 'www.metroshoes.com',
  'brand_name': 'davinchi',
  'sku_number': '14-1382',
  'color': 'black',
  'occasion': 'formal',
  'type': 'derby',
  'extenstion': 'html'},
 {'url': 'https://www.metroshoes.com/metro-33-1385-peach-casual-sandals.html',
  'scheme': 'https',
  'domain': 'www.metroshoes.com',
  'brand_name': 'metro',
  'sku_number': '33-1385',
  'color': 'peach',
  'occasion': 'casual',
  'type': 'sandals',
  'extenstion': 'html'},
 {'url': 'https://www.metroshoes.com/metro-18-1415-maroon-ethnic-pathanis.html',
  'scheme': 'https',
  'domain': 'www.metroshoes.com',
  'brand_name': 'metro',
  'sku_number': '18-1415',
  'color': 'maroon',
  'occasion': 'ethnic',
  'type': 'pathanis',
  'extenstion': 'html'}]

In [81]:
# df[['product_url'],['sku_number']]
# df.info()
df.iloc[19:20]['url']

19    https://www.metroshoes.com/metro-18-19-wine-et...
Name: url, dtype: object

In [73]:
df.head(20)

,url,scheme,domain,brand_name,sku_number,color,occasion,type,extenstion
0,https://www.metroshoes.com/davinchi-60-8-black...,https,www.metroshoes.com,davinchi,60-8,black,casual,slippers,html
1,https://www.metroshoes.com/metro-35-4559-silve...,https,www.metroshoes.com,metro,35-4559,silver,party,slip-ons,html
2,https://www.metroshoes.com/davinchi-14-1382-bl...,https,www.metroshoes.com,davinchi,14-1382,black,formal,derby,html
3,https://www.metroshoes.com/metro-33-1385-peach...,https,www.metroshoes.com,metro,33-1385,peach,casual,sandals,html
4,https://www.metroshoes.com/metro-18-1415-maroo...,https,www.metroshoes.com,metro,18-1415,maroon,ethnic,pathanis,html
5,https://www.metroshoes.com/metro-33-40-black-c...,https,www.metroshoes.com,metro,33-40,black,casual,sandals,html
6,https://www.metroshoes.com/metro-31-78-white-f...,https,www.metroshoes.com,metro,31-78,white,formal,sandals,html
7,https://www.metroshoes.com/davinchi-14-8853-bl...,https,www.metroshoes.com,davinchi,14-8853,black,formal,moccasin,html
8,https://www.metroshoes.com/genx-71-9026-white-...,https,www.metroshoes.com,genx,71-9026,white,casual,sneakers,html
9,https://www.metroshoes.com/skechers-158-246020...,https,www.metroshoes.com,skechers,158-246020,navy,blue,casual-slippers,html
10,https://www.metroshoes.com/davinchi-14-1533-gr...,https,www.metroshoes.com,davinchi,14-1533,grey,formal,moccasin,html
11,https://www.metroshoes.com/activ-328-1117-red-...,https,www.metroshoes.com,activ,328-1117,red,casual,sneakers,html
12,https://www.metroshoes.com/fitflop-338-21-blue...,https,www.metroshoes.com,fitflop,338-21,blue,casual,slippers,html
13,https://www.metroshoes.com/metro-19-150-wine-f...,https,www.metroshoes.com,metro,19-150,wine,formal,moccasin,html
14,https://www.metroshoes.com/metro-71-57-black-c...,https,www.metroshoes.com,metro,71-57,black,casual,loafers,html
15,https://www.metroshoes.com/metro-35-4893-silve...,https,www.metroshoes.com,metro,35-4893,silver,party,sandals,html
16,https://www.metroshoes.com/metro-32-7662-black...,https,www.metroshoes.com,metro,32-7662,black,casual,slippers,html
17,https://www.metroshoes.com/metro-46-5526-tan-c...,https,www.metroshoes.com,metro,46-5526,tan,casual,sneakers,html
18,https://www.metroshoes.com/metro-40-1902-chiku...,https,www.metroshoes.com,metro,40-1902,chiku,party,sandals,html
19,https://www.metroshoes.com/metro-18-19-wine-et...,https,www.metroshoes.com,metro,18-19,wine,ethnic,jutis,html

In [49]:
%store -r csv

In [50]:
csv

,product_url,product_brand,product_name,gender,heel_type,occasion,type,product_price,currency_symbol,product_sizes,size_country,product_colors
0,https://www.metroshoes.com/davinchi-60-8-black...,Davinchi,Black Casual Slippers,Men,Flats,Casual,Slippers,3990.0,Rs,"6,7,8,9,10,11",UK,"black,tan"
1,https://www.metroshoes.com/metro-35-4559-silve...,Metro,Silver Party Slip Ons,Women,Wedges,Party,Slip Ons,2690.0,Rs,"3,4,5,6,7,8",UK,"antique,silver"
2,https://www.metroshoes.com/davinchi-14-1382-bl...,Davinchi,Black Formal Derby,Men,Regular,Formal,Derby,8990.0,Rs,"6,7,8,9,10,11",UK,"black,tan"
3,https://www.metroshoes.com/metro-33-1385-peach...,Metro,Pink Casual Sandals,Women,Flats,Casual,Sandals,1690.0,Rs,"3,4,5,6,7,8",UK,"grey,peach"
4,https://www.metroshoes.com/metro-18-1415-maroo...,Metro,Maroon Ethnic Pathanis,Men,Regular,Ethnic,Pathanis,3690.0,Rs,"6,7,8,9,10,11",UK,"black,tan,maroon"
...,...,...,...,...,...,...,...,...,...,...,...,...
2407,https://www.metroshoes.com/davinchi-14-1397-bl...,Davinchi,Black Formal Moccasin,Men,Regular,Formal,Moccasin,32990.0,Rs,"6,7,8,9,10,11",UK,black
2408,https://www.metroshoes.com/metro-40-2502-black...,Metro,Black Casual Slip Ons,Women,Block,Casual,Slip Ons,2290.0,Rs,"3,4,5,6,7,8",UK,"black,white"
2409,https://www.metroshoes.com/metro-32-1560-tan-c...,Metro,Tan Casual Slip Ons,Women,Flats,Casual,Slip Ons,1690.0,Rs,"3,4,5,6,7,8",UK,"black,tan"
2410,https://www.metroshoes.com/metro-16-306-tan-ca...,Metro,Tan Casual Slippers,Men,Flats,Casual,Slippers,2290.0,Rs,"6,7,8,9,10,11",UK,"black,tan"
2411,https://www.metroshoes.com/id-52-4033-brown-ca...,ID,Brown Casual Sandals,Men,Flats,Casual,Sandals,2585.0,Rs,"6,7,8,9,10,11",UK,"brown,tan"

In [23]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import re
from urllib.parse import urljoin
from price_parser import Price
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from time import sleep,time

In [27]:
'''-------driver setup-------'''
 

url = 'https://www.metroshoes.com/men-shoes.html'

print(len(total_products))

time_taken is:1.3855722030003865
993

In [3]:
df = pd.read_csv('metroshoes.csv')

In [7]:
url = df['product_url'][0]

In [13]:
if url not in list(df['product_url']):
    df['url']

In [16]:
if any(df['product_url'].isin([url])):
    print('yes')

yes

In [35]:
df.groupby('gender')['product_price'].mean()
df['gender'].value_counts()
# df.info()

gender
Women     1312
Men        958
Girls       77
Boys        57
Male        16
women       13
Female       4
Name: count, dtype: int64

In [51]:
df.sort_values(by=['product_price','gender'],ascending=False).head()
# df[df['product_price']==df['product_price'].max()]
Men = df[df['gender']=='Men']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2437 entries, 0 to 2436
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product_url      2437 non-null   object
 1   product_brand    2437 non-null   object
 2   product_name     2437 non-null   object
 3   gender           2437 non-null   object
 4   heel_type        2416 non-null   object
 5   occasion         2437 non-null   object
 6   type             2437 non-null   object
 7   product_price    2437 non-null   float64
 8   currency_symbol  2437 non-null   object
 9   product_sizes    2437 non-null   object
 10  size_country     2437 non-null   object
 11  product_colors   2437 non-null   object
dtypes: float64(1), object(11)
memory usage: 228.6+ KB

In [45]:
Men.shape

(958, 12)

In [49]:
men = Men.sort_index().groupby(['product_price']).head()
men.pivot(columns='product_price',values='')

KeyError: 'mrp'